import json
import uuid

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    status,
)
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.config import settings
from app.db.database import get_database
from app.models import (
    AssistantResponse,
    MeetingSession,
    TranscriptSegment,
)
from app.schemas.assistant import (
    AssistantAnswerResponse,
    AssistantQuestionRequest,
    AssistantResponseRecord,
)
from app.services.speech_service import generate_speech
from app.workflows.assistant_graph import (
    run_assistant_workflow,
)


router = APIRouter(
    prefix="/api/sessions",
    tags=["Assistant"],
)


AI_VOICE_DISCLOSURE = (
    "This voice was generated by artificial intelligence."
)


def get_session_or_404(
    session_id: uuid.UUID,
    database: Session,
) -> MeetingSession:
    meeting_session = database.get(
        MeetingSession,
        session_id,
    )

    if meeting_session is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session was not found.",
        )

    return meeting_session


def validate_deidentified(
    meeting_session: MeetingSession,
) -> None:
    if (
        settings.deidentified_only
        and not meeting_session.deidentified
    ):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                "This prototype only accepts simulated or "
                "fully de-identified educational content."
            ),
        )


@router.post(
    "/{session_id}/ask",
    response_model=AssistantAnswerResponse,
    status_code=status.HTTP_201_CREATED,
)
def ask_assistant(
    session_id: uuid.UUID,
    request: AssistantQuestionRequest,
    database: Session = Depends(get_database),
) -> AssistantAnswerResponse:
    meeting_session = get_session_or_404(
        session_id=session_id,
        database=database,
    )

    validate_deidentified(meeting_session)

    statement = (
        select(TranscriptSegment)
        .where(
            TranscriptSegment.meeting_session_id
            == session_id,
            TranscriptSegment.is_ai_speaker.is_(False),
        )
        .order_by(
            TranscriptSegment.sequence_number.asc()
        )
    )

    segments = list(
        database.scalars(statement).all()
    )

    if not segments:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                "No transcript is available for this session."
            ),
        )

    transcript = "\n".join(
        f"{segment.speaker_name}: {segment.text}"
        for segment in segments
    )

    try:
        answer, web_search_used = run_assistant_workflow(
            session_id=str(session_id),
            question=request.question,
            transcript=transcript,
        )

    except Exception as error:
        print(
            "Assistant workflow error:",
            repr(error),
        )

        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                f"Failed to generate answer: {error}"
            ),
        ) from error

    response_record = AssistantResponse(
        meeting_session_id=session_id,
        command_text=request.question,
        command_type=answer.command_type,
        response_text=answer.answer,
        structured_result=json.loads(
            answer.model_dump_json()
        ),
        audio_file_name=None,
    )

    database.add(response_record)
    database.commit()
    database.refresh(response_record)

    audio_url: str | None = None
    voice: str | None = None
    disclosure: str | None = None
    voice_error: str | None = None

    if request.speak:
        try:
            audio_file_name, _ = generate_speech(
                answer.answer
            )

            response_record.audio_file_name = (
                audio_file_name
            )

            database.commit()
            database.refresh(response_record)

            audio_url = (
                f"/api/audio/{audio_file_name}"
            )

            voice = settings.openai_tts_voice
            disclosure = AI_VOICE_DISCLOSURE

        except Exception as error:
            voice_error = str(error)

            print(
                "Assistant voice-generation error:",
                repr(error),
            )

    return AssistantAnswerResponse(
        response_record=(
            AssistantResponseRecord.model_validate(
                response_record
            )
        ),
        answer=answer,
        web_search_used=web_search_used,
        audio_url=audio_url,
        voice=voice,
        disclosure=disclosure,
        voice_error=voice_error,
    )


@router.get(
    "/{session_id}/responses",
    response_model=list[AssistantResponseRecord],
)
def get_responses(
    session_id: uuid.UUID,
    database: Session = Depends(get_database),
) -> list[AssistantResponseRecord]:
    get_session_or_404(
        session_id=session_id,
        database=database,
    )

    statement = (
        select(AssistantResponse)
        .where(
            AssistantResponse.meeting_session_id
            == session_id
        )
        .order_by(
            AssistantResponse.created_at.asc()
        )
    )

    responses = list(
        database.scalars(statement).all()
    )

    return [
        AssistantResponseRecord.model_validate(
            response
        )
        for response in responses
    ]
