from pathlib import Path

from fastapi import (
    APIRouter,
    HTTPException,
    status,
)
from fastapi.responses import FileResponse

from app.core.config import settings
from app.schemas.speech import (
    SpeechRequest,
    SpeechResponse,
)
from app.services.speech_service import (
    GENERATED_AUDIO_DIRECTORY,
    generate_speech,
    get_audio_path,
)


router = APIRouter(
    tags=["Speech"],
)


AI_VOICE_DISCLOSURE = (
    "This voice was generated by artificial intelligence."
)


@router.post(
    "/api/speech",
    response_model=SpeechResponse,
)
def create_speech(
    request: SpeechRequest,
) -> SpeechResponse:
    try:
        file_name, _ = generate_speech(
            request.text,
        )

        return SpeechResponse(
            audio_file_name=file_name,
            audio_url=f"/api/audio/{file_name}",
            voice=settings.openai_tts_voice,
            disclosure=AI_VOICE_DISCLOSURE,
        )

    except ValueError as error:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(error),
        ) from error

    except Exception as error:
        print(
            "OpenAI speech-generation error:",
            repr(error),
        )

        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "OpenAI voice generation failed. "
                "Check the backend terminal for details."
            ),
        ) from error


@router.get(
    "/api/audio/{file_name}",
    response_class=FileResponse,
)
def serve_audio(
    file_name: str,
) -> FileResponse:
    try:
        audio_path = get_audio_path(file_name)

    except ValueError as error:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(error),
        ) from error

    if not audio_path.exists():
        available = [
            f.name
            for f in GENERATED_AUDIO_DIRECTORY.glob("*.mp3")
        ]
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "message": "Audio file was not found.",
                "requested_file": file_name,
                "audio_directory": str(GENERATED_AUDIO_DIRECTORY),
                "available_files": available,
            },
        )

    return FileResponse(
        path=audio_path,
        media_type="audio/mpeg",
        filename=Path(file_name).name,
    )
